# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DAizlTp-XDjboVDPARx8zdGBDndgsfQP
"""



"""Data analysis

Combine two dataframes and transfer a value from a column in the first dataframe to a different column in the second dataframe during the merge process.
"""

import pandas as pd
import numpy as np

HGNC = pd.read_csv("/content/drive/MyDrive/HOMEO/HGNC-data .csv")
HGNC

GeneDF = pd.read_csv("/content/drive/MyDrive/HOMEO/mergeData.csv")
GeneDF

MGI = pd.read_csv("/content/drive/MyDrive/HOMEO/MGI-data.csv")
MGI

GeneDF.info()

GeneDF['Gene_symbol'] = None

GeneDF

HGNC.info()

# Assuming df1 is your first dataframe and df2 is your second dataframe

# Merge the dataframes based on the conditions
merged_df = pd.merge(GeneDF[GeneDF['Organism'] == 'Human'], HGNC, left_on='GENE NAME FROM ARTICLE', right_on='sep=', how='left')

# Copy values from the desired column
merged_df['Gene_symbol'] = merged_df['Unnamed: 2']

# Drop unnecessary columns
merged_df.drop(['sep=', 'Unnamed: 2'], axis=1, inplace=True)

print(merged_df)

merged_df.info()

merged_df.drop(['Unnamed: 1', 'Unnamed: 4', 'Unnamed: 5'], axis=1, inplace=True)

merged_df

merged_df.rename(columns={'Unnamed: 3': 'Approved name'}, inplace=True)





merged_df.to_csv('Human.csv', index=False)



MGI.head()

MGI.info()

import pandas as pd

# Assuming df1 is your first dataframe and df2 is your second dataframe

# Merge the dataframes based on the conditions
merged_df2 = pd.merge(GeneDF[GeneDF['Organism'] == 'Mouse'], MGI, left_on='GENE NAME FROM ARTICLE', right_on='Input', how='left')

# Copy values from the desired column
merged_df2['Gene_symbol'] = merged_df2['Symbol']

# Drop unnecessary columns
merged_df2.drop(['Input', 'Entrez Gene ID', 'Input Type'], axis=1, inplace=True)
merged_df2

merged_df2.drop(['MGI Gene/Marker ID'], axis=1, inplace=True)

merged_df2.to_csv('Mouse.csv', index=False)